table DimCustomer
	lineageTag: 3272075f-54a5-46e2-8c43-b212e008ca7f

	column CustomerID
		dataType: string
		lineageTag: 66caaaf0-4811-48a3-a7ee-c7eab4e532ff
		summarizeBy: none
		sourceColumn: CustomerID

	column Gender
		dataType: string
		lineageTag: e2db2cfd-4e77-4856-92b6-0191ce74bb89
		summarizeBy: none
		sourceColumn: Gender

	column AgeGroup
		dataType: string
		lineageTag: 7f8e340a-9b87-4963-8e52-30ea79ae8bce
		summarizeBy: none
		sourceColumn: AgeGroup

	column City
		dataType: string
		lineageTag: 2759b4f3-d3a6-47b8-8b59-0abfa17a4800
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

	column Segment
		dataType: string
		lineageTag: 944795dc-be4b-46b9-b8ee-c07403db0de6
		summarizeBy: none
		sourceColumn: Segment

	column SignupDate
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 81d0e40a-414f-46a9-80d6-994447532d20
		summarizeBy: none
		sourceColumn: SignupDate

		variation Variation
			isDefault
			relationship: 07381878-8ed6-4741-bed1-a5e8201419ad
			defaultHierarchy: LocalDateTable_f5960991-54c9-4379-bc6d-f931d40b9818.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column CohortStart
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: cb037970-eb51-4d11-a31e-74f0db753ceb
		summarizeBy: none
		sourceColumn: CohortStart

		variation Variation
			isDefault
			relationship: e27136c9-fdb5-4bae-89a2-ef79bce8d361
			defaultHierarchy: LocalDateTable_7b0d2021-c413-49ff-8a71-aa8f81654609.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column CohortQuarter
		dataType: string
		lineageTag: f77f900c-9f9c-42c6-b59f-2e7f33650be0
		summarizeBy: none
		sourceColumn: CohortQuarter
		sortByColumn: CohortQuarterSort

	column FirstOrderYear
		dataType: int64
		lineageTag: 22a03e46-5072-4483-9a05-f7f157f940a5
		summarizeBy: sum
		sourceColumn: FirstOrderYear

		annotation SummarizationSetBy = Automatic

	column CohortQuarterSort
		dataType: int64
		lineageTag: 64690dbd-3b72-4668-ae94-9b9a342e6e22
		summarizeBy: sum
		sourceColumn: CohortQuarterSort

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Swiftkart/data/DimCustomer.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"CustomerID", type text}, {"Gender", type text}, {"AgeGroup", type text}, {"City", type text}, {"Segment", type text}, {"SignupDate", type date}, {"CohortStart", type date}, {"CohortQuarter", type text}, {"FirstOrderYear", Int64.Type}, {"CohortQuarterSort", Int64.Type}}, "en-US")
				in
				    Typed

