table FactSales
	lineageTag: fa79c81a-35b3-4300-843e-4800591b3829

	column OrderID
		dataType: string
		isHidden
		lineageTag: e4ebd80a-94f3-4ae4-9a63-e5bc186d2eda
		summarizeBy: none
		sourceColumn: OrderID

	column OrderDate
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 4b88c66a-57b1-4892-b19b-870babaa2cf7
		summarizeBy: none
		sourceColumn: OrderDate

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		isHidden
		lineageTag: 51fdbd9f-3ad9-412a-bda9-e9a16e730978
		summarizeBy: none
		sourceColumn: CustomerID

	column ProductID
		dataType: string
		isHidden
		lineageTag: ce32cbc1-030f-4791-8d6d-fdcdaebc5404
		summarizeBy: none
		sourceColumn: ProductID

	column StoreID
		dataType: string
		isHidden
		lineageTag: e77931fe-c4dd-4773-a874-cb202da19a96
		summarizeBy: none
		sourceColumn: StoreID

	column Quantity
		dataType: int64
		isHidden
		lineageTag: a65cb6c6-bf29-4acc-84b0-da52bda7e12e
		summarizeBy: none
		sourceColumn: Quantity

	column UnitPrice
		dataType: double
		isHidden
		lineageTag: dacdde89-e537-45b5-88fd-4f18889ff8f4
		summarizeBy: none
		sourceColumn: UnitPrice

	column DiscountPct
		dataType: double
		isHidden
		lineageTag: d5a731ec-ddad-4612-8a4d-c34b2f6121cc
		summarizeBy: none
		sourceColumn: DiscountPct

	column Revenue
		dataType: double
		isHidden
		lineageTag: d5039645-43f5-4b07-ad5f-2e9da815defa
		summarizeBy: none
		sourceColumn: Revenue

	column Cost
		dataType: double
		isHidden
		lineageTag: ece2670d-6edf-4b88-92e3-822e14926250
		summarizeBy: none
		sourceColumn: Cost

	column PaymentMode
		dataType: string
		lineageTag: e6e5e429-b27e-473c-ad97-2b3e62aaec90
		summarizeBy: none
		sourceColumn: PaymentMode

	column DeliveryMinutes
		dataType: double
		lineageTag: 03048af7-da56-489e-83e7-b65d2d0ec401
		summarizeBy: none
		sourceColumn: DeliveryMinutes

	column ReturnFlag
		dataType: int64
		lineageTag: 258f30f7-d05c-461e-b701-ff9af69d53cb
		summarizeBy: none
		sourceColumn: ReturnFlag

	column Rating
		dataType: int64
		lineageTag: cd7cfe24-b12e-4b30-8620-297624847fa8
		summarizeBy: none
		sourceColumn: Rating

	column Stars
		dataType: string
		lineageTag: 5a493177-c337-4698-961e-ef50ab4ee68a
		summarizeBy: none
		sourceColumn: Stars
		sortByColumn: Rating

	column MonthsAfterFirstOrder
		dataType: int64
		lineageTag: 7e185a33-aa14-4705-a353-fcf5c62836d0
		summarizeBy: none
		sourceColumn: MonthsAfterFirstOrder

	partition FactSales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Swiftkart/data/FactSales.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"ProductID", type text}, {"StoreID", type text}, {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"DiscountPct", type number}, {"Revenue", type number}, {"Cost", type number}, {"PaymentMode", type text}, {"DeliveryMinutes", type number}, {"ReturnFlag", Int64.Type}, {"Rating", Int64.Type}, {"Stars", type text}, {"MonthsAfterFirstOrder", Int64.Type}}, "en-US")
				in
				    Typed

